import Foundation

/// Helper to access bundled resources in both SPM development and standalone app bundle
///
/// IMPORTANT: Bundle.module (auto-generated by SPM) crashes with fatalError when it can't find
/// the resource bundle at expected paths. This happens in release builds installed outside the
/// build directory. We must check Bundle.main FIRST and only use Bundle.module in DEBUG builds.
enum BundleHelper {
    
    // MARK: - App Version
    
    /// Cached Info.plist dictionary (loaded once from source file for debug builds)
    private static let sourceInfoPlist: [String: Any]? = {
        #if DEBUG
        // In debug builds, Bundle.main.infoDictionary is empty because we run as a bare executable.
        // Load Info.plist from the source Resources directory via Bundle.module.
        if let url = lookUp("Info", "plist", nil, in: Bundle.module),
           let data = try? Data(contentsOf: url),
           let plist = try? PropertyListSerialization.propertyList(from: data, format: nil) as? [String: Any] {
            return plist
        }
        #endif
        return nil
    }()
    
    /// The app's marketing version (e.g., "1.0") from Info.plist CFBundleShortVersionString
    static var appVersion: String {
        // Try main bundle first (works in app bundle)
        if let version = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String {
            return version
        }
        // Fall back to source Info.plist (debug builds)
        if let version = sourceInfoPlist?["CFBundleShortVersionString"] as? String {
            return version
        }
        return "1.0"
    }
    
    /// The app's build number (e.g., "1") from Info.plist CFBundleVersion
    static var buildNumber: String {
        // Try main bundle first (works in app bundle)
        if let build = Bundle.main.infoDictionary?["CFBundleVersion"] as? String {
            return build
        }
        // Fall back to source Info.plist (debug builds)
        if let build = sourceInfoPlist?["CFBundleVersion"] as? String {
            return build
        }
        return "1"
    }
    
    /// Full version string combining version and build (e.g., "1.0.1")
    static var fullVersion: String {
        "\(appVersion).\(buildNumber)"
    }
    
    // MARK: - Resources
    
    /// Cached SPM resource bundle for release builds running from build directory
    private static let spmResourceBundle: Bundle? = {
        // When running release build directly from .build directory, resources are in
        // NullPlayer_NullPlayer.bundle next to the executable
        let executableURL = Bundle.main.executableURL ?? URL(fileURLWithPath: CommandLine.arguments[0])
        let buildDir = executableURL.deletingLastPathComponent()
        let spmBundleURL = buildDir.appendingPathComponent("NullPlayer_NullPlayer.bundle")
        if FileManager.default.fileExists(atPath: spmBundleURL.path) {
            return Bundle(url: spmBundleURL)
        }
        return nil
    }()
    
    /// The SwiftPM resource bundle: `Bundle.module` in DEBUG; in release only the copy next to the
    /// executable, since `Bundle.module` crashes when the app runs outside the build directory.
    private static var packageResourceBundle: Bundle? {
        #if DEBUG
        return Bundle.module
        #else
        return spmResourceBundle
        #endif
    }

    /// Looks `name` up in `bundle`, directly or under the copied `Resources/` folder. The package
    /// copies `Resources/` whole (`.copy("Resources")`): the native build system's flat bundle serves
    /// that folder as the bundle's resources, while swiftbuild's `Contents/Resources/` layout nests it
    /// one level down.
    private static func lookUp(_ name: String, _ ext: String?, _ subdirectory: String?, in bundle: Bundle) -> URL? {
        let nested = ["Resources", subdirectory].compactMap { $0 }.joined(separator: "/")
        return bundle.url(forResource: name, withExtension: ext, subdirectory: subdirectory)
            ?? bundle.url(forResource: name, withExtension: ext, subdirectory: nested)
    }

    /// Find a resource URL, checking the main bundle first, then the SwiftPM resource bundle.
    ///
    /// The order is important: Bundle.module crashes in release builds when installed
    /// outside the build directory, so we must try Bundle.main first.
    static func url(forResource name: String, withExtension ext: String?, subdirectory: String? = nil) -> URL? {
        lookUp(name, ext, subdirectory, in: .main)
            ?? packageResourceBundle.flatMap { lookUp(name, ext, subdirectory, in: $0) }
    }
}
