import Foundation

/// Helper to access bundled resources in both SPM development and standalone app bundle
///
/// IMPORTANT: Bundle.module (auto-generated by SPM) crashes with fatalError when it can't find
/// the resource bundle at expected paths. This happens in release builds installed outside the
/// build directory. We must check Bundle.main FIRST and only use Bundle.module in DEBUG builds.
enum BundleHelper {
    
    // MARK: - App Version
    
    /// The app's marketing version (e.g., "1.0") from Info.plist CFBundleShortVersionString
    static var appVersion: String {
        Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "1.0"
    }
    
    /// The app's build number (e.g., "1") from Info.plist CFBundleVersion
    static var buildNumber: String {
        Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "1"
    }
    
    /// Full version string combining version and build (e.g., "1.0.1")
    static var fullVersion: String {
        "\(appVersion).\(buildNumber)"
    }
    
    // MARK: - Resources
    
    /// Returns the bundle containing app resources
    /// - In SPM development: Uses Bundle.module
    /// - In standalone app: Uses Bundle.main's Resources folder
    static var resourceBundle: Bundle {
        #if DEBUG
        // In debug builds, try module bundle first (SPM development)
        return Bundle.module
        #else
        // In release builds, always use main bundle (installed app)
        return Bundle.main
        #endif
    }
    
    /// Find a resource URL, checking main bundle first then module bundle (DEBUG only)
    ///
    /// The order is important: Bundle.module crashes in release builds when installed
    /// outside the build directory, so we must try Bundle.main first.
    static func url(forResource name: String, withExtension ext: String?, subdirectory: String? = nil) -> URL? {
        // Try main bundle first (works in standalone app)
        if let url = Bundle.main.url(forResource: name, withExtension: ext, subdirectory: subdirectory) {
            return url
        }
        
        // Try main bundle Resources subdirectory (common app bundle structure)
        if let subdirectory = subdirectory {
            if let url = Bundle.main.url(forResource: name, withExtension: ext, subdirectory: "Resources/\(subdirectory)") {
                return url
            }
        }
        
        // Try without subdirectory in main bundle
        if let url = Bundle.main.url(forResource: name, withExtension: ext) {
            return url
        }
        
        // Try main bundle Resources folder directly
        if let resourceURL = Bundle.main.resourceURL {
            var searchURL = resourceURL.appendingPathComponent(name)
            if let ext = ext {
                searchURL = searchURL.appendingPathExtension(ext)
            }
            if FileManager.default.fileExists(atPath: searchURL.path) {
                return searchURL
            }
            
            // Also try with subdirectory
            if let subdirectory = subdirectory {
                var subSearchURL = resourceURL.appendingPathComponent(subdirectory).appendingPathComponent(name)
                if let ext = ext {
                    subSearchURL = subSearchURL.appendingPathExtension(ext)
                }
                if FileManager.default.fileExists(atPath: subSearchURL.path) {
                    return subSearchURL
                }
            }
        }
        
        #if DEBUG
        // Only try Bundle.module in DEBUG builds - it crashes in release builds
        // when the app is installed outside the SPM build directory
        if let url = Bundle.module.url(forResource: name, withExtension: ext, subdirectory: subdirectory) {
            return url
        }
        #endif
        
        return nil
    }
    
    /// Find a resource URL in a specific subdirectory
    static func url(forResource name: String, withExtension ext: String?, inDirectory directory: String) -> URL? {
        return url(forResource: name, withExtension: ext, subdirectory: directory)
    }
    
    /// Get the path to the Presets directory
    static var presetsDirectory: URL? {
        // Try main bundle first (standalone app)
        if let url = Bundle.main.url(forResource: "Presets", withExtension: nil) {
            return url
        }
        if let resourceURL = Bundle.main.resourceURL {
            let presetsURL = resourceURL.appendingPathComponent("Presets")
            if FileManager.default.fileExists(atPath: presetsURL.path) {
                return presetsURL
            }
            // Also try Resources/Presets
            let resourcePresetsURL = resourceURL.appendingPathComponent("Resources").appendingPathComponent("Presets")
            if FileManager.default.fileExists(atPath: resourcePresetsURL.path) {
                return resourcePresetsURL
            }
        }
        
        #if DEBUG
        // Only try Bundle.module in DEBUG builds
        if let url = Bundle.module.url(forResource: "Presets", withExtension: nil, subdirectory: "Resources") {
            return url
        }
        if let url = Bundle.module.url(forResource: "Presets", withExtension: nil) {
            return url
        }
        #endif
        
        return nil
    }
    
    /// Get the path to the Textures directory
    static var texturesDirectory: URL? {
        // Try main bundle first (standalone app)
        if let url = Bundle.main.url(forResource: "Textures", withExtension: nil) {
            return url
        }
        if let resourceURL = Bundle.main.resourceURL {
            let texturesURL = resourceURL.appendingPathComponent("Textures")
            if FileManager.default.fileExists(atPath: texturesURL.path) {
                return texturesURL
            }
            // Also try Resources/Textures
            let resourceTexturesURL = resourceURL.appendingPathComponent("Resources").appendingPathComponent("Textures")
            if FileManager.default.fileExists(atPath: resourceTexturesURL.path) {
                return resourceTexturesURL
            }
        }
        
        #if DEBUG
        // Only try Bundle.module in DEBUG builds
        if let url = Bundle.module.url(forResource: "Textures", withExtension: nil, subdirectory: "Resources") {
            return url
        }
        if let url = Bundle.module.url(forResource: "Textures", withExtension: nil) {
            return url
        }
        #endif
        
        return nil
    }
    
    /// Get the path to a skin file (wsz)
    static func skinURL(named name: String) -> URL? {
        return url(forResource: name, withExtension: "wsz")
    }
}
