#!/usr/bin/env swift
// generate_default_wal_skin.swift
//
// Generates the placeholder `.wal` skin that ships with Modern mode:
// Sources/NullPlayer/Resources/Skins/NullPlayer-Black.wal
//
// NullPlayer bundles no Winamp skins. Modern mode needs *something* to load on a
// first run, so this writes a deliberately plain skin of our own — a flat panel,
// artwork-less Wasabi standard controls, and the transport actions the engine
// already answers. It is a starting point, not a skin anyone is meant to keep:
// users import their own `.wal` from the Modern menu.
//
// Run: swift scripts/generate_default_wal_skin.swift

import AppKit
import Foundation

let skinName = "NullPlayer-Black"

// MARK: - Geometry
//
// One fixed-size window. Nothing here resizes, so every rect is a literal and the
// layout declares the same number for default/minimum/maximum.

let windowWidth = 300
let windowHeight = 118

// MARK: - The one bitmap
//
// A layout with no resolvable `background=` falls back to the palette's content
// colour, but that path exists for skins that reference Winamp's own base skin —
// reaching it deliberately would record a resourceMissing diagnostic against our
// own default. So the panel is a real 8x8 swatch, stretched by the layout.

func writeBackground(to path: String) {
    let size = 8
    guard let rep = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: size, pixelsHigh: size,
        bitsPerSample: 8, samplesPerPixel: 4,
        hasAlpha: true, isPlanar: false,
        colorSpaceName: .deviceRGB,
        bytesPerRow: size * 4, bitsPerPixel: 32
    ) else {
        fatalError("Unable to allocate the background bitmap")
    }
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
    NSColor(deviceRed: 32 / 255, green: 32 / 255, blue: 36 / 255, alpha: 1).setFill()
    NSRect(x: 0, y: 0, width: size, height: size).fill()
    NSGraphicsContext.restoreGraphicsState()
    guard let data = rep.representation(using: .png, properties: [:]) else {
        fatalError("Unable to encode the background bitmap")
    }
    try! data.write(to: URL(fileURLWithPath: path))
}

// MARK: - skin.xml

let skinXML = """
<WinampAbstractionLayer version="1.35">

  <!--
    NullPlayer's placeholder Modern skin.

    Written by hand and generated by scripts/generate_default_wal_skin.swift; no
    Winamp asset is bundled or copied. Every control below is either an artwork-less
    Wasabi standard widget or a plain <text>, so the whole skin is one 8x8 swatch and
    this file.
  -->

  <skininfo>
    <name>Default Skin (Black)</name>
    <version>1.0</version>
    <author>NullPlayer</author>
    <comment>Placeholder skin for Modern mode. Import a .wal skin to replace it.</comment>
  </skininfo>

  <bitmap id="np.panel" file="background.png"/>

  <color id="np.text" value="224,224,224"/>
  <color id="np.dim" value="144,144,150"/>

  <!-- What NullPlayer draws on its own surfaces (playlist, equalizer) inside this skin. -->
  <color id="wasabi.list.text" value="224,224,224"/>
  <color id="wasabi.list.background" value="24,24,28"/>
  <color id="wasabi.list.text.selected.background" value="52,86,140"/>

  <container id="main" name="Default Skin (Black)">
    <layout id="normal" background="np.panel"
            default_w="\(windowWidth)" default_h="\(windowHeight)"
            minimum_w="\(windowWidth)" minimum_h="\(windowHeight)"
            maximum_w="\(windowWidth)" maximum_h="\(windowHeight)">

      <!-- Title strip. The layout itself is the drag handle. -->
      <text id="np.name" x="8" y="4" w="200" h="14" text="NullPlayer" color="np.dim"/>
      <Wasabi:Button id="np.minimize" x="256" y="3" w="16" h="16" text="_"
                     color="np.dim" action="MINIMIZE"/>
      <Wasabi:Button id="np.close" x="276" y="3" w="16" h="16" text="x"
                     color="np.dim" action="CLOSE"/>

      <!-- Readouts. -->
      <text id="np.song" x="8" y="22" w="284" h="16" display="songname" color="np.text"/>
      <text id="np.elapsed" x="8" y="42" w="80" h="14" display="time" color="np.dim"/>
      <text id="np.length" x="212" y="42" w="80" h="14" display="songlength" align="right"
            color="np.dim"/>

      <!-- Seek. -->
      <Wasabi:HSlider id="np.seek" x="8" y="60" w="284" h="10" color="np.text" action="seek"/>

      <!-- Transport. -->
      <Wasabi:Button id="np.prev"  x="8"   y="76" w="38" h="20" text="|&lt;"  color="np.text" action="PREV"/>
      <Wasabi:Button id="np.play"  x="49"  y="76" w="38" h="20" text="&gt;"   color="np.text" action="PLAY"/>
      <Wasabi:Button id="np.pause" x="90"  y="76" w="38" h="20" text="||"     color="np.text" action="PAUSE"/>
      <Wasabi:Button id="np.stop"  x="131" y="76" w="38" h="20" text="[]"     color="np.text" action="STOP"/>
      <Wasabi:Button id="np.next"  x="172" y="76" w="38" h="20" text="&gt;|"  color="np.text" action="NEXT"/>
      <Wasabi:Button id="np.ml"    x="215" y="76" w="44" h="20" text="ML"     color="np.text"
                     action="TOGGLE" param="guid:ml" tooltip="Media Library"/>
      <Wasabi:Button id="np.pl"    x="263" y="76" w="29" h="20" text="PL"     color="np.text"
                     action="TOGGLE" param="guid:pl" tooltip="Playlist"/>

      <!-- Volume. -->
      <Wasabi:HSlider id="np.volume" x="8" y="102" w="284" h="8" color="np.text" action="volume"/>

    </layout>
  </container>

</WinampAbstractionLayer>
"""

// MARK: - Build

let fm = FileManager.default
let repoRoot = URL(fileURLWithPath: fm.currentDirectoryPath)
let output = repoRoot.appendingPathComponent("Sources/NullPlayer/Resources/Skins/\(skinName).wal")

let staging = repoRoot.appendingPathComponent("tmp/\(skinName)-build", isDirectory: true)
try? fm.removeItem(at: staging)
try! fm.createDirectory(at: staging, withIntermediateDirectories: true)

try! skinXML.write(to: staging.appendingPathComponent("skin.xml"), atomically: true, encoding: .utf8)
writeBackground(to: staging.appendingPathComponent("background.png").path)

let archive = staging.appendingPathComponent("\(skinName).wal")
let zip = Process()
zip.executableURL = URL(fileURLWithPath: "/usr/bin/zip")
zip.currentDirectoryURL = staging
zip.arguments = ["-j", "-X", archive.path, "skin.xml", "background.png"]
try! zip.run()
zip.waitUntilExit()
guard zip.terminationStatus == 0 else {
    FileHandle.standardError.write(Data("ERROR: zip failed (\(zip.terminationStatus))\n".utf8))
    exit(1)
}

try? fm.removeItem(at: output)
try! fm.createDirectory(at: output.deletingLastPathComponent(), withIntermediateDirectories: true)
try! fm.copyItem(at: archive, to: output)
try? fm.removeItem(at: staging)

print("Wrote \(output.path)")
