#!/bin/bash
# Generate the aggregated third-party notices artifact from the manifest.
#
# Reads scripts/third_party_components.tsv and concatenates, for every
# component, an attribution header followed by the full required license text
# into Sources/NullPlayer/Resources/ThirdPartyLicenses/ThirdPartyNotices.txt.
#
# Run this whenever the manifest or any bundled dependency changes, then commit
# the regenerated ThirdPartyNotices.txt. See docs/third-party-notices.md.
#
# Usage:
#   ./scripts/generate_third_party_notices.sh
#   ./scripts/generate_third_party_notices.sh --output /tmp/ThirdPartyNotices.txt

set -eo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT=$(pwd)

MANIFEST="$REPO_ROOT/scripts/third_party_components.tsv"
RES_DIR="$REPO_ROOT/Sources/NullPlayer/Resources"
OUT="$RES_DIR/ThirdPartyLicenses/ThirdPartyNotices.txt"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            OUT="${2:-}"
            if [[ -z "$OUT" ]]; then
                echo "✗ --output requires a path" >&2
                exit 2
            fi
            shift 2
            ;;
        *)
            echo "✗ Unknown argument: $1" >&2
            exit 2
            ;;
    esac
done

if [[ ! -f "$MANIFEST" ]]; then
    echo "✗ Manifest not found: $MANIFEST" >&2
    exit 1
fi

APP_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$RES_DIR/Info.plist" 2>/dev/null || echo "")

tmp=$(mktemp)
{
    echo "NullPlayer — Third-Party Software Notices"
    [[ -n "$APP_VERSION" ]] && echo "NullPlayer version $APP_VERSION"
    echo "Generated by scripts/generate_third_party_notices.sh"
    echo ""
    echo "This file aggregates the license notices for every third-party"
    echo "component that ships inside the NullPlayer application bundle —"
    echo "Swift packages compiled into the binary, bundled frameworks and"
    echo "dynamic libraries, native source ports, fonts, and bundled assets."
    echo ""
    echo "The individual license texts are also shipped as separate files under"
    echo "Resources/ThirdPartyLicenses/ inside the app bundle."
    echo ""
} > "$tmp"

count=0
missing=0
while IFS=$'\t' read -r key name spdx copyright url version license_text bundle_glob; do
    # Skip comments and blank lines
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    count=$((count + 1))

    {
        echo "================================================================================"
        echo "$name"
        echo "================================================================================"
        echo "License:    $spdx"
        echo "Copyright:  $copyright"
        echo "Source:     $url"
        echo "Version:    $version"
        echo ""
    } >> "$tmp"

    license_path="$RES_DIR/$license_text"
    if [[ -f "$license_path" ]]; then
        cat "$license_path" >> "$tmp"
    else
        echo "✗ Missing license text for '$name': $license_text" >&2
        missing=$((missing + 1))
        echo "[MISSING LICENSE TEXT: $license_text]" >> "$tmp"
    fi
    echo "" >> "$tmp"
    echo "" >> "$tmp"
done < "$MANIFEST"

if [[ "$missing" -gt 0 ]]; then
    rm -f "$tmp"
    echo "✗ $missing license text file(s) missing — not writing $OUT" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUT")"
mv "$tmp" "$OUT"
echo "✓ Wrote $OUT ($count components)"
